/**
 * FROZEN scene registry-format contract (phase-5.md §0.7).
 *
 * These types encode the `registry/index.json` schema — GENERATED by the kit
 * (Group A) and CONSUMED by a future CLI pass via the JSON on disk. The JSON
 * index is the ONLY cross-package seam: the scene-kit owns its OWN registry
 * types and does NOT import `@butai/slide-kit`'s (no cross-package coupling —
 * the same discipline P3 established).
 *
 * Mirrors slide-kit's `registry-types.ts` shape, adapted for scenes: a scene is
 * a standalone `.html` document + its `.frame.md` design-spec. Scenes are
 * framework-free and standalone, so `dependencies` (npm) and
 * `registryDependencies` (other scene ids) are expected empty.
 *
 * Extend only via additive OPTIONAL fields; never rename an existing field or
 * change `registryVersion` semantics without a breaking-schema bump.
 */

/** Item classification. The scene-kit ships exactly one type this phase. */
export type SceneRegistryItemType = 'registry:scene';

/** Where a copied file lands in the consumer: `.html` → scenes, `.frame.md` → specs. */
export type SceneRegistryFileTarget = 'scenes' | 'specs';

/** One file belonging to a scene registry item. `sha256` hashes the RAW source
 *  — drift detection and provenance headers anchor on it. */
export type SceneRegistryFile = { path: string; target: SceneRegistryFileTarget; sha256: string };

export type SceneRegistryItem = {
  id: string;
  type: SceneRegistryItemType;
  title: string;
  category: string;
  /** The `.html` + `.frame.md` (`.meta.md` is catalog input, not a shipped file). */
  files: SceneRegistryFile[];
  /** npm deps — expected empty (framework-free). */
  dependencies: string[];
  /** other scene ids — expected empty (scenes are standalone). */
  registryDependencies: string[];
};

export type SceneRegistryIndex = {
  name: string;
  version: string;
  registryVersion: number;
  /** sha256 over the sorted items — deterministic, NO timestamps. */
  contentHash: string;
  items: SceneRegistryItem[];
};
