/**
 * @butai/docs-kit — doc-pattern catalog metadata (GENERATED by
 * `pnpm --filter @butai/docs-kit gen`). Do not edit by hand.
 *
 * Isomorphic: a plain data array re-exported from the root barrel so browser
 * bundles get the pattern metas without touching `@butai/patterns/node`.
 */
import type { PatternMeta } from "@butai/patterns";

export const PATTERNS: PatternMeta[] = [
  {
    "id": "doc-footer",
    "name": "Doc Footer",
    "kind": "page",
    "category": "closing",
    "description": "The close — a \"what's next\" band with a call to action, plus a muted footer meta line. Ends with forward momentum, not a summary.",
    "snippet": "<!-- doc-footer — the CTA band deepens the accent/green; a theme repaints it -->\n<footer class=\"doc-footer\">\n  <div class=\"band\">\n    <div><h3>What happens next</h3><p>Pick the patterns you need.</p></div>\n    <a class=\"btn\" href=\"https://example.com\">Get started</a>\n  </div>\n  <div class=\"foot\"><span>Last updated 2026-01-01</span> · <span>example.com</span></div>\n</footer>",
    "engine": "none",
    "tags": [
      "page",
      "closing",
      "cta",
      "footer"
    ],
    "source": {
      "file": "patterns/doc-footer.meta.md"
    }
  },
  {
    "id": "code-block",
    "name": "Code Block",
    "kind": "page",
    "category": "code",
    "description": "A terminal window plus a code viewer, both hand-highlighted with span classes (no highlight.js, no CDN) — a command session and a focused source excerpt.",
    "snippet": "<!-- code-block — hand-highlighted spans, no highlight.js; each maps to a contract token -->\n<div class=\"term\">\n  <div class=\"body\"><span class=\"p\">$</span> <span class=\"cmd\">docs gen</span>\n<span class=\"ok\">&#10003;</span> <span class=\"o\">cataloged 12 patterns</span></div>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "code",
      "terminal",
      "viewer"
    ],
    "source": {
      "file": "patterns/code-block.meta.md"
    }
  },
  {
    "id": "card-grid",
    "name": "Card Grid",
    "kind": "page",
    "category": "content",
    "description": "A responsive 2/3-column grid of cards — each a title row with status badges, a body, and a muted meta footer. The default unit for a titled item with tags and a note.",
    "snippet": "<!-- card-grid — a titled item with status badges + a muted meta footer -->\n<div class=\"grid cols-3\">\n  <div class=\"card\">\n    <div class=\"card-head\"><h3>First item</h3><span class=\"badge is-shipped\">shipped</span></div>\n    <p>A plain-English line on what this item is.</p>\n    <div class=\"card-meta\">Owner · <b>Team A</b></div>\n  </div>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "content",
      "grid",
      "cards"
    ],
    "source": {
      "file": "patterns/card-grid.meta.md"
    }
  },
  {
    "id": "comparison",
    "name": "Comparison",
    "kind": "page",
    "category": "data",
    "description": "A side-by-side pair — a before/other side (warm tint) versus an after/ours side (green tint), each with a mono label. The core X vs Y device.",
    "snippet": "<!-- comparison — side.a and side.b tint the status palette; a theme repaints both -->\n<div class=\"pair\">\n  <div class=\"side a\"><span class=\"lbl\">Before</span><p>Every doc was hand-styled.</p></div>\n  <div class=\"side b\"><span class=\"lbl\">After</span><p>One token set repaints them all.</p></div>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "data",
      "compare",
      "before-after"
    ],
    "source": {
      "file": "patterns/comparison.meta.md"
    }
  },
  {
    "id": "data-table",
    "name": "Data Table",
    "kind": "page",
    "category": "data",
    "description": "A full-width comparison table — hairline rows, uppercase-mono headers, and two tinted compared columns (one muted, one in a status color).",
    "snippet": "<!-- data-table — td.a is muted, td.b takes a status color; a theme repaints them -->\n<table>\n  <tr><th>Capability</th><th>Baseline</th><th>This approach</th></tr>\n  <tr><td><b>Build step</b></td><td class=\"a\">required</td><td class=\"b\">none</td></tr>\n</table>",
    "engine": "none",
    "tags": [
      "page",
      "data",
      "table",
      "comparison"
    ],
    "source": {
      "file": "patterns/data-table.meta.md"
    }
  },
  {
    "id": "metric-grid",
    "name": "Metric Grid",
    "kind": "page",
    "category": "data",
    "description": "A trio of counted stat cards — a mono kicker, a big number in a status color, and a caption. The scannable summary after a grouped section.",
    "snippet": "<!-- metric-grid — the big number takes a status color; a theme repaints the palette -->\n<div class=\"metric-grid\">\n  <div class=\"metric ok\"><span class=\"k\">shipped</span><span class=\"n\">12</span><p>patterns cataloged.</p></div>\n  <div class=\"metric warn\"><span class=\"k\">planned</span><span class=\"n\">4</span><p>queued next.</p></div>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "data",
      "metrics",
      "tally"
    ],
    "source": {
      "file": "patterns/metric-grid.meta.md"
    }
  },
  {
    "id": "callout",
    "name": "Callout",
    "kind": "page",
    "category": "emphasis",
    "description": "The thesis highlight — a faint accent wash behind a 1px accent border, holding the one line that matters.",
    "snippet": "<!-- callout — the wash and border both derive from the accent; a theme repaints them -->\n<div class=\"callout\">\n  <span class=\"lbl\">Thesis</span>\n  <b>The single sentence the reader should leave with.</b> Everything else supports this claim.\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "emphasis",
      "thesis"
    ],
    "source": {
      "file": "patterns/callout.meta.md"
    }
  },
  {
    "id": "quote-band",
    "name": "Quote Band",
    "kind": "page",
    "category": "emphasis",
    "description": "A full-bleed brand band holding one pull-quote — light text on a tinted accent surface. Use at most once or twice per document.",
    "snippet": "<!-- quote-band — the band surface is the accent deepened; a theme repaints it -->\n<figure class=\"quote-band\">\n  <div class=\"mark\">The turn</div>\n  <blockquote>Same markup, different tokens: a theme repaints the whole document.</blockquote>\n  <figcaption class=\"cite\">example.com · design notes</figcaption>\n</figure>",
    "engine": "none",
    "tags": [
      "page",
      "emphasis",
      "quote",
      "band"
    ],
    "source": {
      "file": "patterns/quote-band.meta.md"
    }
  },
  {
    "id": "doc-hero",
    "name": "Doc Hero",
    "kind": "page",
    "category": "header",
    "description": "Brief/report opener — a mono eyebrow, one tight display headline with one accent word, a one-line summary, and a meta row of date + status badges.",
    "snippet": "<!-- doc-hero — the header block; a theme repaints the eyebrow/accent via the token contract -->\n<header class=\"doc-hero\">\n  <div class=\"meta\"><span>2026-01-01</span> · <span class=\"badge is-shipped\">shipped</span></div>\n  <div class=\"eyebrow\">Example.com · Report</div>\n  <h1>One tight headline, <span class=\"accent\">one clear idea</span></h1>\n  <p class=\"sub\">A one-line summary of what this document argues, in plain language.</p>\n</header>",
    "engine": "none",
    "tags": [
      "page",
      "header",
      "opener"
    ],
    "source": {
      "file": "patterns/doc-hero.meta.md"
    }
  },
  {
    "id": "decisions",
    "name": "Decisions",
    "kind": "page",
    "category": "structure",
    "description": "A numbered locked-decisions list, ADR-style — a chip digit, a title, and a muted rationale, one row per decision.",
    "snippet": "<!-- decisions — the chip digit takes the accent; a theme repaints it -->\n<div class=\"decisions\">\n  <div class=\"dec\">\n    <span class=\"num\">1</span>\n    <div class=\"body\"><h3>The locked choice</h3><p>Why it was made, in one line.</p></div>\n  </div>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "structure",
      "decisions",
      "adr"
    ],
    "source": {
      "file": "patterns/decisions.meta.md"
    }
  },
  {
    "id": "section-header",
    "name": "Section Header",
    "kind": "page",
    "category": "structure",
    "description": "Section marker — an uppercase mono eyebrow (the lead one takes the accent) above an h2 with a hairline underline. Paces a document into scannable sections.",
    "snippet": "<!-- section-header — the lead eyebrow takes the accent; a theme repaints it -->\n<div class=\"section-header\">\n  <span class=\"eyebrow lead\">Overview</span>\n  <h2>What this section is about</h2>\n</div>",
    "engine": "none",
    "tags": [
      "page",
      "structure",
      "section"
    ],
    "source": {
      "file": "patterns/section-header.meta.md"
    }
  },
  {
    "id": "timeline",
    "name": "Timeline",
    "kind": "page",
    "category": "structure",
    "description": "A vertical stepped sequence with counter chips down the left, plus a compact horizontal flow-pipeline variant for a left-to-right process.",
    "snippet": "<!-- timeline — the counter chips take the accent; a theme repaints them -->\n<ol class=\"steps\">\n  <li><b>Author the pattern</b> <span>as a self-contained fragment.</span></li>\n  <li><b>Catalog it</b> <span>deterministically.</span></li>\n</ol>",
    "engine": "none",
    "tags": [
      "page",
      "structure",
      "steps",
      "flow"
    ],
    "source": {
      "file": "patterns/timeline.meta.md"
    }
  }
];
