/**
 * FROZEN doc-pattern registry-format contract (phase-6.md §0.6).
 *
 * These types encode the `registry/index.json` schema — GENERATED by the kit
 * (Group A) and CONSUMED by a future CLI pass via the JSON on disk. The JSON
 * index is the ONLY cross-package seam: the docs-kit owns its OWN registry
 * types and does NOT import `@butai/slide-kit`'s or `@butai/scene-kit`'s (no
 * cross-package coupling — the same discipline P3 established).
 *
 * Mirrors scene-kit's `registry-types.ts` shape, adapted for doc patterns: a
 * doc pattern is a self-contained `.html` fragment (its `.meta.md` is catalog
 * input, not a shipped file). Doc patterns are framework-free and standalone,
 * so `dependencies` (npm) and `registryDependencies` (other pattern ids) are
 * expected empty.
 *
 * The index is generated in this frozen shape so a future CLI pass can
 * `butai add <doc-pattern>` trivially — wiring the CLI is NOT this phase
 * (a logged GAP; `@butai/cli` stays byte-untouched to protect P3's slide
 * copy-in).
 *
 * Extend only via additive OPTIONAL fields; never rename an existing field or
 * change `registryVersion` semantics without a breaking-schema bump.
 */

/** Item classification. The docs-kit ships exactly one type this phase. */
export type DocRegistryItemType = 'registry:doc-pattern';

/** Where a copied file lands in the consumer: `.html` → pages. */
export type DocRegistryFileTarget = 'pages';

/** One file belonging to a doc-pattern registry item. `sha256` hashes the RAW
 *  source — drift detection and provenance headers anchor on it. */
export type DocRegistryFile = { path: string; target: DocRegistryFileTarget; sha256: string };

export type DocRegistryItem = {
  id: string;
  type: DocRegistryItemType;
  title: string;
  category: string;
  /** The `.html` (`.meta.md` is catalog input, not a shipped file). */
  files: DocRegistryFile[];
  /** npm deps — expected empty (framework-free). */
  dependencies: string[];
  /** other pattern ids — expected empty (patterns are self-contained). */
  registryDependencies: string[];
};

export type DocRegistryIndex = {
  name: string;
  version: string;
  registryVersion: number;
  /** sha256 over the sorted items — deterministic, NO timestamps. */
  contentHash: string;
  items: DocRegistryItem[];
};
