/**
 * FROZEN registry-format contract (phase-3.md §0.4).
 *
 * These types encode the `registry/index.json` schema — GENERATED by the kit
 * (Group A) and CONSUMED by the CLI (Group B) via the JSON on disk. The JSON
 * index is the ONLY cross-package seam: the CLI re-declares its own view of the
 * relevant shapes (see `@butai/cli` config-types) rather than importing these.
 *
 * Extend only via additive OPTIONAL fields; never rename an existing field or
 * change `registryVersion` semantics without a breaking-schema bump.
 */

/** Item classification. The catalog lists only `registry:slide`; the index
 *  lists all three (the CLI needs primitives/styles to resolve closures). */
export type RegistryItemType = 'registry:slide' | 'registry:primitive' | 'registry:style';

/** Where a copied file lands in the consumer — maps to a `butai.json` alias key. */
export type RegistryFileTarget = 'slides' | 'primitives' | 'styles';

/** One file belonging to a registry item. `sha256` hashes the RAW source
 *  (pre-rewrite) — drift detection and provenance headers anchor on it. */
export type RegistryFile = {
  path: string; // repo-relative, e.g. "src/slides/cover-slide.tsx"
  target: RegistryFileTarget;
  sha256: string;
};

/** How the CLI rewrites a single import specifier at `add` time.
 *  - `registry`: resolves to another item's file → rewrite to `<alias>/<item>`
 *  - `external`: `@butai/*` or npm → left untouched */
export type ImportMapEntry =
  | { kind: 'registry'; item: string; alias: RegistryFileTarget }
  | { kind: 'external' };

/** Per-file rewrite table: original import specifier → how to rewrite it. */
export type FileImportMap = Record<string, ImportMapEntry>;

export type RegistryItem = {
  id: string; // kebab-case, unique in the index
  type: RegistryItemType;
  title: string;
  category: string;
  files: RegistryFile[];
  /** Other item ids to pull in the copy closure. */
  registryDependencies: string[];
  /** npm packages to install (e.g. "qrcode.react"). */
  dependencies: string[];
  /** workspace packages the copy assumes present (e.g. "@butai/deck"). */
  butaiDependencies: string[];
  /** Keyed by file path (from `files[].path`) → per-import rewrite table. */
  importMap: Record<string, FileImportMap>;
};

export type RegistryIndex = {
  name: string; // "@butai/slide-kit"
  version: string; // package version, e.g. "0.0.1"
  registryVersion: number; // bump only on a breaking schema change
  contentHash: string; // sha256 over the sorted items — deterministic, NO timestamps
  items: RegistryItem[];
};
